export default [
  {
    name: 'GraphQuill',
    image: 'graphquill-logo.png',
    description: 'GraphQL DevTool to query your API from VSCode, written in TypeScript & Node.js',
    websiteImage: 'vscode.svg',
    websiteName: 'VSCode MarketPlace',
    website: 'https://marketplace.visualstudio.com/items?itemName=sproutdeveloping.graphquill',
    githubOwner: 'oslabs-beta',
    githubRepo: 'GraphQuill',
  }, {
    name: 'Dockerized GraphQL API',
    image: 'graphql-api.png',
    description: 'A Dockerized GraphQL API made during development of GraphQuill',
    githubOwner: 'GraphQuill',
    githubRepo: 'Mock-GraphQL-API-Docker',
  }, {
    name: 'SocketMan',
    image: 'socketman.png',
    description: 'WebSockets-based Multiplayer Hangman Game',
    // website: 'https://socket-man.herokuapp.com/',
    // websiteImage: 'heroku.svg',
    // websiteName: 'Play here!',
    github: 'https://github.com/alexchao26/SocketMan/',
    githubOwner: 'alexchao26',
    githubRepo: 'SocketMan',
  }, {
    name: 'Personal  Website',
    image: 'beaker.svg',
    description: 'This website, built in Next.js',
    github: 'https://github.com/alexchao26/personal-site-nextjs',
    website: 'https://alexchao.dev',
    websiteName: 'alexchao.dev',
    websiteImage: 'beaker.svg',
    githubOwner: 'alexchao26',
    githubRepo: 'personal-site-nextjs',
  },
];
