export default [
  {
    name: 'GraphQuill',
    image: '/images/graphquill-logo.png',
    description: 'GraphQL DevTool to query your API from VSCode - Written in Node.js TypeScript',
    websiteImage: '/images/vscode.svg',
    websiteName: 'VSCode MarketPlace',
    website: 'https://marketplace.visualstudio.com/items?itemName=sproutdeveloping.graphquill',
    githubOwner: 'oslabs-beta',
    githubRepo: 'GraphQuill',
  }, {
    name: 'Dockerized GraphQL API',
    image: '/images/graphql-api.png',
    description: 'A Dockerized GraphQL API made during development of GraphQuill',
    githubOwner: 'GraphQuill',
    githubRepo: 'Mock-GraphQL-API-Docker',
  }, {
    name: 'SocketMan',
    image: '/images/socketman.png',
    description: 'Multiplayer Hangman using WebSockets, React/Redux, Node.js/Express, & NoSQL',
    website: 'https://socket-man.herokuapp.com/',
    websiteImage: '/images/heroku.svg',
    websiteName: 'Play here!',
    github: 'https://github.com/alexchao26/SocketMan/',
    githubOwner: 'alexchao26',
    githubRepo: 'SocketMan',
  }, {
    name: 'Personal  Website',
    image: 'images/beaker.svg',
    description: 'This website, built in NextJS',
    github: 'https://github.com/alexchao26/personal-site-nextjs',
    website: 'https://alexchao.dev',
    websiteName: 'alexchao.dev',
    websiteImage: '/images/beaker.svg',
    githubOwner: 'alexchao26',
    githubRepo: 'personal-site-nextjs',
  },
];
